platform :ios, '13'
use_modular_headers!

target 'XRatesKitExample' do
  pod 'XRatesKit.swift', :path => '../'
  pod 'HsToolKit.swift', git: 'https://github.com/horizontalsystems/hs-tool-kit-ios'
  pod 'CoinKit.swift', git: 'https://github.com/horizontalsystems/coin-kit-ios'

  pod 'SnapKit'
  pod 'Chart.swift'
end

target 'XRatesKitTests' do
  pod 'XRatesKit.swift', :path => '../'
end
