platform :ios, '11'
use_modular_headers!

target 'XRatesKitExample' do
  pod 'XRatesKit.swift', :path => '../'

  pod 'SnapKit'
  pod 'Chart.swift'
end

target 'XRatesKitTests' do
  pod 'XRatesKit.swift', :path => '../'
end
