import Foundation

class CoinMap {

    static let coinToPaprikaCoin = [
        "BTC": "btc-bitcoin",
        "ETH": "eth-ethereum",
        "BCH": "bch-bitcoin-cash",
        "DASH": "dash-dash",
        "ANKR": "ankr-ankr-network",
        "BAT": "bat-basic-attention-token",
        "BNB": "bnb-binance-coin",
        "BNT": "bnt-bancor",
        "BTCB": "btcb-bitcoin-bep2",
        "CAS": "cas-cashaa",
        "CRO": "cro-cryptocom-chain",
        "CRPT": "crpt-crypterium",
        "DAI": "dai-dai",
        "DGD": "dgd-digixdao",
        "DGX": "dgx-digix-gold-token",
        "ELF": "elf-aelf",
        "ENJ": "enj-enjin-coin",
        "EOS": "eos-eos",
        "EOSDT": "eosdt-eosdt",
        "EURS": "eurs-stasis-eurs",
        "GNT": "gnt-golem",
        "GUSD": "gusd-gemini-dollar",
        "GTO": "gto-gifto",
        "HOT": "hot-holo",
        "HT": "ht-huobi-token",
        "IDEX": "idex-idex",
        "IDXM": "idxm-idex-membership",
        "IQ": "iq-everipedia",
        "KCS": "kcs-kucoin-shares",
        "KNC": "knc-kyber-network",
        "LINK": "link-chainlink",
        "LOOM": "loom-loom-network",
        "LRC": "lrc-loopring",
        "MANA": "mana-decentraland",
        "MCO": "mco-mco",
        "MEETONE": "meetone-meetone",
        "MITH": "mith-mithril",
        "MKR": "mkr-maker",
        "NEXO": "nexo-nexo",
        "NPXS": "npxs-pundi-x",
        "NUT": "nut-nut",
        "OMG": "omg-omisego",
        "ORBS": "orbs-orbs",
        "PAX": "pax-paxos-standard-token",
        "PGL": "pgl-prospectors-gold",
        "POLY": "poly-polymath",
        "PPT": "ppt-populous",
        "PTI": "pti-paytomat",
        "R": "r-revain",
        "REP": "rep-augur",
        "SNT": "snt-status",
        "TUSD": "tusd-trueusd",
        "USDC": "usdc-usd-coin",
        "USDT": "usdt-tether",
        "WAX": "wax-wax",
        "WTC": "wtc-waltonchain",
        "ZIL": "zil-zilliqa",
        "ZRX": "zrx-0x",
    ]

}
